[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimize = true
optimizer_runs = 1000000
via-ir = false


[fmt]
int_types = "preserve"

[profile.test-no-ir]
via-ir = false
snapshots = "snapshots/no-ir"

[profile.test-via-ir]
via-ir = true
snapshots = "snapshots/via-ir"
